### ISSUE TITLE
Lien mort dans "First steps with the API"

### ISSUE THREAD

**Issue by sebj54** [ovh/docs#112]
Bonjour,

Le lien https://eu.api.ovh.com/1.0/auth/credential est mort. Il se trouve sur cette page : https://docs.ovh.com/gb/en/customer/first-steps-with-ovh-api/ au deuxième paragraphe.

Merci d'avance !

**Comment by sebj54** [comment]
En fait, je viens de comprendre ce qui ne va pas : 
Il est écrit "To do so, you have to go to https://eu.api.ovh.com/1.0/auth/credential to specify the access you require" alors qu'en réalité on doit faire un appel POST via `curl` pour spécifier les permissions qu'on souhaite. 

Ça n'est pas clair du tout pour le premier venu et de plus, il n'y a pas de liste des permissions qu'on peut demander (un lien vers la liste https://api.ovh.com/console/ pourrait suffire).

**Comment by StevenSoulet** [comment]
Maj faite depuis un bon moment, close issue.
