### ISSUE TITLE
Swift ObjectStorage 'X-Container-Meta-Access-Control-Allow-Origin' does not allow wildcard (*)

### ISSUE THREAD

**Issue by stouch** [ovh/docs#2348]
I tried to contact OVH support about this, but not answer :

In https://docs.ovh.com/gb/en/storage/pca/swift-commands-memo/ , nothing is said about the possibility to put a wildcard (`*`) in  X-Container-Meta-Access-Control-Allow-Origin , but in https://docs.ovh.com/fr/storage/pcs/cors/ , it is said : " L’utilisation des wildcard est autorisé mais non recommandé : `http://*.example.com` "

Actually, I tested it, and wildcard DOES NOT seem to work in X-Container-Meta-Access-Control-Allow-Origin ( we can only set an exhaustive list of sub domains and the root domain, which is very annoying ). 

Could we mention it in the documentation ? Why is it not possible to use wildcard ?

Regards.

**Comment by OVH-Team-Guides** [comment]
Hello @stouch , thank you for alerting us about this.
The related documentation has just been updated: https://github.com/ovh/docs/pull/2394
Here is the updated section in English: https://github.com/ovh/docs/blob/develop/pages/cloud/storage/pcs-cors/guide.en-gb.md#cors-metadata-definition
Best regards.
