### ISSUE TITLE
Tutorial "How to deploy a web service for Yolov5 using your own weights with Flask", index.html is missing.

### ISSUE THREAD

**Issue by RRighart** [ovh/docs#2713]
Hi, I have found your tutorial « How to deploy a web service for YOLOv5 using your own weights with Flask » at https://docs.ovh.com/gb/en/ai-training/web-service-yolov5/ which is very interesting. 
I am trying your code but it seems to me that index.html is missing. Would be great if you could add that file. Thank you in advance !

**Comment by baaastijn** [comment]
> Hi, I have found your tutorial « How to deploy a web service for YOLOv5 using your own weights with Flask » at https://docs.ovh.com/gb/en/ai-training/web-service-yolov5/ which is very interesting. I am trying your code but it seems to me that index.html is missing. Would be great if you could add that file. Thank you in advance !

Hello !
You can find the whole code on Github link : 
https://github.com/ovh/ai-training-examples/tree/main/jobs/flask/yolov5-web-service

Have a good day ! Tell us if it's solved
