### ISSUE TITLE
Please explain PCS usage with a PCA account

### ISSUE THREAD

**Issue by thierrybo** [ovh/docs#34]
Hi,

as I have a PCA account, I was waiting for duplicity 0.8 release since 8 months as it is supposed to handle PCA.   
However in your article I see you use both a PCS and PCA account.  Does this mean that we need to buy another PCS account just to make our PCA backups working with duplicity?

If this is the case, please state it clearly in the article content.

**Comment by Fracasx** [comment]
Hi @thierrybo , I think that for this question you should have a faster answer directly on our Community forums where you have directly administrators and advanced users.

EN version: https://community.ovh.com/en/
FR version: https://community.ovh.com/

Honestly I never tested Duplicity so hard to give you a precise answer.
