### ISSUE TITLE
Zonemaster documentation

### ISSUE THREAD

**Issue by hannaeko** [ovh/docs#3401]
Hello,
Zonemaster developer here, I see that the [Zonemaster](https://zonemaster.net) related documentation has been removed in commit https://github.com/ovh/docs/commit/430aff753fccbc5860930dee6c299c10d8d63601 because it was flagged being deprecated. While the documentation (mainly the screenshots) was outdated the tool is very much still in development and can be used to test dns zones configuration.
Members of the Zonemaster team are willing to update the documentation if that can help to have it back.
Thanks,
Gaël Berthaud-Müller

**Comment by OVH-Team-Guides** [comment]
Hello Gaël,
We retired this documentation as it was outdated. Some of our customers were also worried about warnings displayed on Zonemaster with regards to their DNS configuration though, in reality, there were no misconfigurations on their OVHcloud services which do have some limitations.
We will be considering a restoration of the guide soon and we appreciate your offer to provide us with updates. We will let you know when we've made significant progress on it.
Thanks,
Yoann Cosse

**Comment by BrenKt** [comment]
Hello Gaël,
Can you take a look at our new proposition?
#3471
For the moment there's only an FR version, tell me if you need to review it in EN.
If this version is ok for you, we can translate it into other languages.

**Comment by hannaeko** [comment]
Hello,
Thank you for your reactivity! French is alright for us, I will forward it to the team and we will review.

**Comment by hannaeko** [comment]
Hello,
The documentation looks good to us, thanks! It will probably need some update when the next release is out in November or December.
When the release is ready, do you prefer that we create a PR with the updates or that we create a issue and let you open the PR?

**Comment by OVH-Team-Guides** [comment]
Hello,
Thanks for your feedback, we will now translate and deploy the guide.
Feel free to do a PR when the next release is out.
Best regards,
Yoann

**Comment by OVH-Team-Guides** [comment]
Hello Gaël, we deployed the new version of the tutorial today on all our subs. Here is the FR version: https://docs.ovh.com/fr/domains/ovhcloud-domain-zonemaster-tutorial/
Best regards,
Yoann

**Comment by hannaeko** [comment]
Thank you!
