### ISSUE TITLE
Error when running a k8s guide

### ISSUE THREAD

**Issue by plyd** [ovh/docs#424]
When we run step by step [this guide](https://github.com/ovh/docs/blob/develop/pages/platform/kubernetes-k8s/setting-up-a-persistent-volume/guide.en-gb.md), we run a problem

    Events:
      Type     Reason              Age                   From                         Message
      ----     ------              ----                  ----                         -------
      Warning  ProvisioningFailed  81s (x26 over 7m25s)  persistentvolume-controller  storageclass.storage.k8s.io "cinder-high-speed" not found

because

    storageClassName: cinder-high-speed
does not work, (not found).
I think it should be replaced by:

     storageClassName: csi-cinder-high-speed

**Comment by LostInBrittany** [comment]
Indeed, from Kubernetes 1.15.x, the `storageClassName` must indeed be `csi-cinder-high-speed`.

For Kubernetes clusters running in versions 1.12.x, 1.13.x and 1.14.x the storageClassName should be: `cinder-high-speed`.

It's already fixed, we can close the issue.

**Comment by OVH-Team-Guides** [comment]
Issue is fixed. Thanks for alerting us.
