### ISSUE TITLE
Change command in IP aliasing guide

### ISSUE THREAD

**Issue by jhoangqm** [ovh/docs#439]
Command needs to be changed on this [guide](https://docs.ovh.com/gb/en/dedicated/network-ipaliasing/#cpanel_1)

Step 3: Restart the interface
You now need to restart your interface:
/etc/init.d/ipaliases restart

"/etc/init.d/ipaliases restart" returns : 

[root@centos ~]# /etc/init.d/ipaliases restart
-bash: /etc/init.d/ipaliases: No such file or directory

**Correct command:**
[root@centos ~]# /etc/init.d/network restart
Restarting network (via systemctl):

**Comment by OVH-Team-Guides** [comment]
Hi, sorry for late answer.

Guide information is not wrong but might be confusing. Step 3 under "cPanel" refers to OVH template "Cpanel on CentOS 6" and it still works as described.

Later versions of CentOS will produce an error but the instructions under "CentOS and Fedora (25 and earlier)" do not advise to use this command anyway. Step 3 here:

You now need to start your alias interface:
ifup eth0:0

Guides will be updated for clarification.

Thanks for that alert. 
Regards,
The OVH guides team.
