### ISSUE TITLE
where do i get my credentials informations after identifing

### ISSUE THREAD

**Issue by HADDADENICAR** [ovh/docs#444]
after identifing , in order to generate a token to be able to call the api from c#, we 've filled [this form](https://eu.api.ovh.com/createToken/) , but we didn't get the token informations :

- Application Key (identifie votre application)
- Application Secret (authentifie votre application)
- Consumer Key (autorise l’application à accéder aux méthodes choisies)

where can i find this generated fields ?

**Comment by valentinocossar** [comment]
Hi, I've the same issue, I don't know where I can edit, revoke or list generated tokens. Can you help me?
