### ISSUE TITLE
pgvector plan ?

### ISSUE THREAD

**Issue by guillim** [ovh/docs#4596]
Hi,

I am wondering if there is any plan to add the postgers extension "[pgvector](https://github.com/pgvector/pgvector)" to your managed Postgres ? I dont' see it here : [postgresql_02_extensions/guide.en-us.md](https://github.com/ovh/docs/blob/develop/pages/platform/databases/postgresql_02_extensions/guide.en-us.md)

FYI : Amazon redshift already intergrated it

**Comment by thild42** [comment]
Hey @guillim,
You might want to check our public roadmap for databases: https://github.com/ovh/public-cloud-roadmap/projects/2
As for your question regarding the support of pgvector, it is currently not planned.
I will raise this topic internally.
Thank you for your feedback

**Comment by thild42** [comment]
To follow up on this topic, we are working on supporting "pgvector".
No ETA yet but it should happen in the next few weeks.

**Comment by guillim** [comment]
@jmoyson could be a good option for a managed database migration

**Comment by thild42** [comment]
@guillim it is coming!

👉 https://github.com/ovh/public-cloud-roadmap/issues/427
