### ISSUE TITLE
S3 HTTPS

### ISSUE THREAD

**Issue by fpillotovh** [ovh/docs#4738]
As a past techwriter, I would like to create this issue concerning the guide: https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-static-website-https?id=kb_article_view&sysparm_article=KB0058097 ...
I was opposed to it after OVH's VTT because it didn't offer ssl ... but this is even worse :
- the dig command is totally wrong as the answer indicates
- the site given as an example no longer exists??

**Comment by lason-ovh** [comment]
> As a past techwriter, I would like to create this issue concerning the guide: https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-static-website-https?id=kb_article_view&sysparm_article=KB0058097 ... I was opposed to it after OVH's VTT because it didn't offer ssl ... but this is even worse :
> 
>     * the dig command is totally wrong as the answer indicates
> 
>     * the site given as an example no longer exists?? mega lol for a major european hoster

Hi, thanks for the feedback.

Do you care to explain why "this is even worse"?

As for the dig command, maybe replacing it with a simple host command would be enough.

Finally, yes indeed the site given as example is no longer exists, we will edit the documentation to remove the part mentioning it.

**Comment by fpillotovh** [comment]
> Do you care to explain why "this is even worse"?

no documentation is better than lousy documentation ... then it all depends on the image you want to convey about the company that hires you.

The `dig` command could simply have been corrected by adding the `{bucket}`in it, the `host` command works even though it's not recommended in terms of best practices.

**Comment by lason-ovh** [comment]
> 
> The `dig` command could simply have been corrected by adding the `{bucket}`in it, the `host` command works even though it's not recommended in terms of best practices.

Thanks for your remark, yes indeed host is not recommended but we will keep the documentation as simple as possible as the main purpose here is to do a very simple dns lookup, so the example will be replaced with a host cmd.
However, we will mention in the doc that a dig or a host cmd can be used to do that.
