### ISSUE TITLE
Broken link 'Order your Metrics project'

### ISSUE THREAD

**Issue by wilfriedroset** [ovh/docs#48]
Hi,

Will reading the documentation about 'order your metrics project' on the following page: https://docs.ovh.com/fr/metrics/order/, I found a broken link shortly after 'step 5 Grab your endpoints'. The link points to: https://docs.ovh.com/fr/metrics/protocol-overview, which is currently 404

Cheers,
W.

**Comment by wilfriedroset** [comment]
Found another broken link on the same page 'Push and vizualize your first datapoints with OpenTSDB'. This one points to: https://docs.ovh.com/fr/metrics/start-opentsdb, which is currently 404.

**Comment by Fracasx** [comment]
Hi @wilfriedroset , it's fixed. Thank you.
