### ISSUE TITLE
Note that RISE servers are not compatible with vRack

### ISSUE THREAD

**Issue by jefft** [ovh/docs#4844]
I have just had confirmed with tech support that bare metal rise servers (https://www.ovhcloud.com/en-au/bare-metal/rise/) cannot be added to a vRack.

This fact is not mentioned in the documentation.  May I suggest that this line:
https://github.com/ovh/docs/blob/7eb4d4dacbb5bbfaf1b2a76f98d5fceb17c17c8a/pages/cloud/dedicated/vrack_configuring_on_dedicated_server/guide.en-au.md?plain=1#L23

be expanded to: "Note that RISE dedicated servers are not compatible".

**Comment by gary-ovh** [comment]
Newer RISE servers are now vRack compatible
