### ISSUE TITLE
documentation for Terraform S3 Backend outdated

### ISSUE THREAD

**Issue by Mx7ca** [ovh/docs#5430]
Hello,
I've just updated my Terraform version to `v1.6.4` and received an error when using OVH S3 Object Storage as a backend. The backend is configured as explained in [the documentation](https://help.ovhcloud.com/csm/en-public-cloud-compute-terraform-high-perf-object-storage-backend-state?id=kb_article_view&sysparm_article=KB0051345#initializing-terraform-configuration). Also switching back to version `v1.5.7`, it works again, so it's not a problem with my configuration.
The error looks like this:
![Screenshot_20231125_121428](https://github.com/ovh/docs/assets/45539900/95e94630-97c6-4e87-a99f-2c9eae186f31)

Checking out [the Terraform S3 Backend documentation](https://developer.hashicorp.com/terraform/language/settings/backends/s3#s3-1), I was able to fix the configuration:
![Screenshot_20231125_121714](https://github.com/ovh/docs/assets/45539900/de028862-1d5f-4715-9625-fed72e1a8976)
With this new configuration it works without any warnings/errors.

The documentation should be updated.

Best regards,
Maximilian Müller

**Comment by scraly** [comment]
Thanks for the issue, and for the PR, we will update it! :)

**Comment by le0nld** [comment]
@Mx7ca Hi,
could you share you .aws/config  & credentials structure, pls.
I successfully connected to ovh s3 in console, but I got error in terraform

` Error: Error copying state from the previous "local" backend to the newly configured
│ "s3" backend:
│     failed to upload state: operation error S3: PutObject, https response error StatusCode: 400, RequestID: txce34fdf4c0004e91bd86f-0065a01da1, HostID: txce34fdf4c0004e91bd86f-0065a01da1, api error InvalidArgument: Invalid Argument.
│ 
│ The state in the previous backend remains intact and unmodified. Please resolve
│ the error above and try again.
`

main.tf

``` required_version = ">= 1.6"

  backend "s3" {
    profile = "ovh-dev"
    bucket = "iac-state"
    key    = "terraform.dev"
    region = "de"
    endpoints = {
      s3 = "https://s3.de.io.cloud.ovh.net"
    }
    skip_credentials_validation = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
  }
```
  
config 
```
[profile ovh-dev]
region = de
endpoint_url = https://s3.de.io.cloud.ovh.net
```

Credentials
```
[ovh-dev]
aws_access_key_id=...
aws_secret_access_key=...
```


locally request:
```
aws s3 ls --profile ovh-dev

2024-01-10 18:33:35 iac-state
```

**Comment by Mx7ca** [comment]
Hey @leonidstakhovsky 
my configuration looks similarly to yours. I was just trying to work with it again and got the same response. But it seems that by now the [documentation](https://help.ovhcloud.com/csm/en-public-cloud-compute-terraform-high-perf-object-storage-backend-state?id=kb_article_view&sysparm_article=KB0051345#initializing-terraform-configuration) has been updated again and a new parameter
```
skip_s3_checksum            = true
```
has been added. It fixed the issue at least for me.
