### ISSUE TITLE
Aucune image / no image

### ISSUE THREAD

**Issue by Snowbaha** [ovh/docs#56]
Toutes les src des images ne fonctionnent pas sur la page : https://docs.ovh.com/fr/dedicated/services-backup-storage/

Exemple : https://vgy.me/xpHA2M.png et https://vgy.me/aJf7Gr.png

**Comment by Fracasx** [comment]
Bonjour @Snowbaha ,

Ca fonctionne en effet beaucoup moins bien sans les images à jour. Je fix ça avant demain midi sans faute. Merci pour la remontée.

**Comment by Fracasx** [comment]
C'est corrigé @Snowbaha  merci pour m'avoir averti en tout cas.

**Comment by Snowbaha** [comment]
Pas de soucis :) Merci pour la rapidité
