### ISSUE TITLE
Hi, ovh team! Happy holidays It seems that now ovh public cloud supports ed25519 you might want to update the docs

### ISSUE THREAD

**Issue by alexandreelise** [ovh/docs#5600]
Hi,

I'm a long time happy client of ovh. It seems that now ed25519 keys are supported in Ovh Public Cloud SSH keys section.

You might want to update the docs:

https://help.ovhcloud.com/csm/en-public-cloud-compute-additional-ssh-keys?id=kb_article_view&sysparm_article=KB0050568

https://help.ovhcloud.com/csm/en-public-cloud-compute-getting-started?id=kb_article_view&sysparm_article=KB0051009

Thanks for adding this useful feature.

PS: Keep on your good work. Keep expanding around the World. The Sky is NOT the limit.

Have a delightful day and enjoy your holidays. Take care.

**Comment by Jessica41** [comment]
Hello @alexandreelise we're delighted to hear from you and greatly appreciate your comments! the necessary updates have been made to the guides concerned and will be online today.

Happy new year to you.

**Comment by OVH-Team-Guides** [comment]
Related PR: https://github.com/ovh/docs/pull/5628
