### ISSUE TITLE
Ask about DISK FULL mode

### ISSUE THREAD

**Issue by vinhnd20** [ovh/docs#6132]
I wonder if other operations such as BACKUP, FAILOVER, ... can still work when the disk full mode is turned on. Can someone explain it for me ? https://help.ovhcloud.com/csm/en-public-cloud-databases-handling-disk-full?id=kb_article_view&sysparm_article=KB0057424

**Comment by BellionBastien** [comment]
Hello @vinhnd20, whenever a database service is in disk full mode, AKA read only. Your service will still continue to work as usual, backups are made on the same schedule as usual, fail-over mechanism is still triggered whenever a node is detected as non functional.

As explained in the doc, the only change you see is that you are no longer able to write data on your service until you added storage capacity or deleted some data on your service.

**Comment by vinhnd20** [comment]
Thank you.
