### ISSUE TITLE
Outdated Public Cloud to vRack article

### ISSUE THREAD

**Issue by sfxworks** [ovh/docs#625]
https://github.com/ovh/docs/blob/develop/pages/cloud/dedicated/configuring-the-vrack-between-the-public-cloud-and-a-dedicated-server/guide.en-gb.md

These options aren't the same as the updated interface. I can only add a new private network and do not see options to add an existing vrack.

**Comment by sfxworks** [comment]
Found the updated guide https://support.us.ovhcloud.com/hc/en-us/articles/360002093130-How-to-Configure-vRack-for-Public-Cloud-Services

**Comment by bs-ovh** [comment]
Hello!
Thank you for your request. The outdated guide is currently being updated for docs.ovh.com. It will be replaced by a more extensive version, covering multiple interfaces (& APIs). It will be online very soon!

Best,
OVHcloud guides team
