### ISSUE TITLE
Rendering bug

### ISSUE THREAD

**Issue by JeanCollas** [ovh/docs#79]
This page:

https://github.com/ovh/docs/blob/master/pages/cloud/storage/pca_dev/guide.en-gb.md

has a rendering bug at the middle of the page:

https://docs.ovh.com/gb/en/storage/pca/dev/

![image](https://user-images.githubusercontent.com/3519393/44222158-fd76a900-a183-11e8-9911-24c960d2edc9.png)

**Comment by Fracasx** [comment]
Hi @JeanCollas ,

It's fixed, thanks for informing me.

**Comment by JeanCollas** [comment]
@Fracasx 
Much easier to read!

Few bugs:
"Further unsealing requests will have no other effect than polling the operation ETA.

See further explanations about this request." <= this link is broken

As well as "See greater details about this request." in Getting a container inventory section.
They seem to not be able to resolve file name of the pages

**Comment by Fracasx** [comment]
@JeanCollas  should be better now, I fixed the links, they look correct. Can you double check and tell me?

**Comment by JeanCollas** [comment]
Links look fine to me now :)

**Comment by Fracasx** [comment]
Perfect :) Have a good day and thanks for your help.
